### ISSUE TITLE
Steep transformation of logistic curve for weighting function

### ISSUE THREAD

**Issue by dakkusingh** [jaimindp/dollar_cost_average_dip_buying#2]
`fg_weight = -2/(1+np.exp(-0.17*(self.fear_greed_value-50)))+2`

Hi,
Any chance you can help me understand how this function works?

**Comment by jaimindp** [comment]
Hey,

Take a look at the notebook:
https://github.com/jaimindp/dollar_cost_average_dip_buying/blob/main/backtest_dca_analysis.ipynb

There are a bunch of functions with different curves. This one is the
logistic curve.

All the best!

Jaimin

**Comment by dakkusingh** [comment]
Thanks a lot for the quick reply Jaimin. Very useful!
